name: flutter_tools
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  get: 4.6.5
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
  flutter_easyloading: ^3.0.5
  device_info_plus: 4.0.0
  permission_handler: ^10.0.0
  lpinyin: ^2.0.3
  sp_util: ^2.0.3
  image_picker: ^0.8.5+3
  url_launcher: 6.1.5
  flutter_widget_from_html: ^0.8.5
  scrollable_positioned_list: ^0.2.3
  flutter_screenutil: ^5.5.3+2
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  #  下面的tabbar
  convex_bottom_bar: ^3.0.0
  date_format: 2.0.6

  oktoast: ^3.2.0

  # 通知
  flutter_local_notifications: ^9.8.0+1
  # text动画
  animated_text_kit: ^4.2.2


#//connectivity_plus for checking wifi connection status
  connectivity_plus: ^2.3.6+1
#//network_info_plus
  network_info_plus: ^2.1.4+1
  convert: ^3.0.2
  crypto: ^3.0.2


#  flutter_vpn: ^0.12.0
  socks5: ^0.1.2
  vpn_check: ^0.1.0
#  flutter_openvpn: ^0.2.0


  #  flutter_socks_proxy: ^0.0.2


  flutter_native_timezone: ^2.0.0
  http: ^0.13.4
  image: ^3.0.8
  path_provider: ^2.0.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.1



  native_flutter_proxy: ^0.1.15
  system_proxy: ^0.1.0



  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:
  assets:
    - assets/images/
    - assets/images/nine
    - assets/video/
    - assets/data/
  uses-material-design: true
